name: quiz
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # GÃ©nÃ©ration d'UUID (optionnel)
  uuid: ^4.2.1

  # State & routing
  flutter_riverpod: ^2.0.0
  go_router: ^6.0.0

  # Networking & storage
  dio: ^5.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^8.0.0
  crypto: ^3.0.2
  http: ^1.2.0

  # UI helpers
  flutter_svg: ^1.1.0

  # Icons iOS style
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^1.1.0
  build_runner: ^2.4.0
  # ðŸ”¥ ICÃ”NES DE Lâ€™APPLICATION
  flutter_launcher_icons: ^0.13.1
# ðŸ”¥ CONFIGURATION DU LOGO (NE PAS METTRE DANS flutter:)
flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/logo.png

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/logoo.png
    - assets/questions/

